---
- hosts: localhost
  connection: local
  become: true

  tasks:

  # Preparation tasks

  - name: upgrade system
    pacman:
      update_cache: yes
      upgrade: yes

  # Common packages

  - name: install common packages
    package:
      name:
        # General
        - tmux

        # File Browsers
        - nemo
